### PR TITLE
Refactored and updated instructions

### PR DESCRIPTION
**Pull request by amirfuhrmann**
I refactored the code, such that it can create a publishable package, and can be isntalled via pip directly from git

also updated the instructions so that the installation procedure and the usage are clearer

### CODE REVIEW

**Comment by nghiant2710** [comment]
@amirfuhrmann Thank you very much for your PR. We already have a big PR to officially release resin python sdk that fixes all the issue you're having, change api endpoints to our production servers and include documentation about the sdk. I will let you know as soon as the python sdk is released.

**Comment by petrosagg** [comment]
@amirfuhrmann this is good to merge. Do you mind if I squash some of the commits to make the history cleaner?

**Comment by amirfuhrmann** [comment]
of course — no  issue.

Amir

---

Amir Fuhrmann, afuhrmann@gmail.com, 408-391-8533

**Comment by petrosagg** [comment]
Merged manually, you can see the history here: https://github.com/resin-io-projects/resin-python-wrapper/commits/master

Cheers!

**Pull request closed without merging**
